[package]
name = "hbakd"
version = "0.1.0-dev"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hbak_common = { version = "0.1.0-dev", path = "../hbak_common" }
